import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { Download, Eye, Share2 } from "lucide-react";
import { IntelErrorState, IntelSkeleton } from "@/components/analyst/StatePanels";
import { reportsQuery } from "@/lib/intelligence-api";
import { useAnalystScope } from "@/lib/analyst-filters";

export const Route = createFileRoute("/analyst/reports")({
  head: () => ({
    meta: [
      { title: "Intelligence Reports — CORTEX Crime Analyst" },
      {
        name: "description",
        content:
          "Executive, district, category, hotspot, forecast and network analysis dossiers generated by the Crime Intelligence Runtime.",
      },
      { property: "og:title", content: "Intelligence Reports — CORTEX Crime Analyst" },
      { property: "og:description", content: "Official generated intelligence dossiers." },
      { name: "robots", content: "noindex" },
    ],
  }),
  component: ReportsPage,
});

function ReportsPage() {
  const { filters, reset } = useAnalystScope();
  const reports = useQuery(reportsQuery(filters));
  const [preview, setPreview] = useState<string | null>(null);

  return (
    <div className="p-4">
      <header className="mb-4">
        <h1 className="font-display text-lg font-semibold">Intelligence Reports</h1>
        <div className="label-meta mt-1">
          Generated dossiers for the current scope · classification enforced by the runtime
        </div>
        <div className="ksp-rule mt-3 h-px w-24 opacity-70" />
      </header>

      {reports.isLoading ? (
        <IntelSkeleton rows={8} />
      ) : reports.isError ? (
        <IntelErrorState onRetry={() => reports.refetch()} onChangeFilters={reset} />
      ) : (
        <div className="grid gap-px bg-border lg:grid-cols-2">
          {reports.data?.map((r) => (
            <article key={r.id} className="bg-card">
              <header className="flex items-start justify-between gap-3 border-b border-border px-3 py-2.5">
                <div className="min-w-0">
                  <div className="label-official truncate text-xs">{r.title}</div>
                  <div className="label-meta mt-0.5 truncate">
                    {r.id} · {r.pages} pp · {r.classification}
                  </div>
                </div>
                <span className="label-meta shrink-0 !text-[9px]">{r.kind}</span>
              </header>

              <div className="px-3 py-2.5">
                <p className="text-[11px] text-muted-foreground">{r.summary}</p>
                <dl className="mt-2 grid grid-cols-2 gap-2">
                  <div>
                    <dt className="label-meta">Scope</dt>
                    <dd className="truncate font-mono text-[10px] text-foreground">{r.scope}</dd>
                  </div>
                  <div>
                    <dt className="label-meta">Period</dt>
                    <dd className="font-mono text-[10px] text-foreground">{r.period}</dd>
                  </div>
                </dl>

                {preview === r.id && (
                  <div className="mt-3 border border-khaki/30 bg-surface/25 p-3">
                    <div className="label-official text-[11px]">Preview · sections</div>
                    <ol className="mt-1.5 space-y-1">
                      {r.sections.map((s, i) => (
                        <li key={s} className="font-mono text-[10px] text-muted-foreground">
                          {String(i + 1).padStart(2, "0")} · {s}
                        </li>
                      ))}
                    </ol>
                    <div className="label-meta mt-2">
                      Rendered {new Date(r.generatedAt).toISOString().slice(0, 10)} by the Crime
                      Intelligence Runtime
                    </div>
                  </div>
                )}
              </div>

              <footer className="flex flex-wrap items-center gap-2 border-t border-border px-3 py-2">
                <button
                  onClick={() => setPreview(preview === r.id ? null : r.id)}
                  className="inline-flex h-8 items-center gap-1.5 border border-primary/60 px-2.5 font-mono text-[10px] uppercase tracking-[0.14em] text-primary transition-colors hover:bg-primary/10"
                >
                  <Eye className="size-3" />
                  {preview === r.id ? "Hide" : "Preview"}
                </button>
                <button className="btn-exec h-8 px-2.5 !text-[10px]">
                  <Download className="size-3" />
                  Download PDF
                </button>
                <button className="inline-flex h-8 items-center gap-1.5 border border-border px-2.5 font-mono text-[10px] uppercase tracking-[0.14em] text-muted-foreground transition-colors hover:text-foreground">
                  <Share2 className="size-3" />
                  Share
                </button>
              </footer>
            </article>
          ))}
        </div>
      )}
    </div>
  );
}
