/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalystRouteImport } from './routes/analyst'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as InvestigatorRouteImport } from './routes/investigator'
import { Route as PolicymakerRouteImport } from './routes/policymaker'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SupervisorRouteImport } from './routes/supervisor'
import { Route as AnalystIndexRouteImport } from './routes/analyst.index'
import { Route as AnalystCniRouteImport } from './routes/analyst.cni'
import { Route as AnalystPciRouteImport } from './routes/analyst.pci'
import { Route as AnalystReportsRouteImport } from './routes/analyst.reports'
import { Route as AnalystSciRouteImport } from './routes/analyst.sci'
import { Route as ApiCasesRouteImport } from './routes/api/cases'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiDeploymentRouteImport } from './routes/api/deployment'
import { Route as ApiHistoryRouteImport } from './routes/api/history'
import { Route as ApiNetworkRouteImport } from './routes/api/network'
import { Route as ApiOrdersRouteImport } from './routes/api/orders'
import { Route as ApiPolicyImpactRouteImport } from './routes/api/policy-impact'
import { Route as ApiPolicySimulationRouteImport } from './routes/api/policy-simulation'
import { Route as ApiPredictionsRouteImport } from './routes/api/predictions'
import { Route as ApiReportsRouteImport } from './routes/api/reports'
import { Route as ApiResourcePlanningRouteImport } from './routes/api/resource-planning'
import { Route as ApiThreatsRouteImport } from './routes/api/threats'
import { Route as InitializeRoleRouteImport } from './routes/initialize.$role'
import { Route as InvestigatorIndexRouteImport } from './routes/investigator.index'
import { Route as InvestigatorBipRouteImport } from './routes/investigator.bip'
import { Route as InvestigatorCinRouteImport } from './routes/investigator.cin'
import { Route as InvestigatorHistoryRouteImport } from './routes/investigator.history'
import { Route as PolicymakerIndexRouteImport } from './routes/policymaker.index'
import { Route as PolicymakerImpactRouteImport } from './routes/policymaker.impact'
import { Route as PolicymakerReportsRouteImport } from './routes/policymaker.reports'
import { Route as PolicymakerResourcesRouteImport } from './routes/policymaker.resources'
import { Route as PolicymakerStrategyRouteImport } from './routes/policymaker.strategy'
import { Route as SupervisorIndexRouteImport } from './routes/supervisor.index'
import { Route as SupervisorDeploymentRouteImport } from './routes/supervisor.deployment'
import { Route as SupervisorOperationsRouteImport } from './routes/supervisor.operations'
import { Route as SupervisorOrdersRouteImport } from './routes/supervisor.orders'
import { Route as SupervisorThreatsRouteImport } from './routes/supervisor.threats'
import { Route as WorkspaceRoleRouteImport } from './routes/workspace.$role'
import { Route as ApiCaseCaseIdRouteImport } from './routes/api/case.$caseId'
import { Route as ApiDecisionScenarioRouteImport } from './routes/api/decision.scenario'
import { Route as ApiDistrictOperationsRouteImport } from './routes/api/district.operations'
import { Route as ApiDistrictOverviewRouteImport } from './routes/api/district.overview'
import { Route as ApiGovernanceDashboardRouteImport } from './routes/api/governance.dashboard'
import { Route as ApiGovernanceQueryRouteImport } from './routes/api/governance.query'
import { Route as ApiGovernanceStrategyRouteImport } from './routes/api/governance.strategy'
import { Route as ApiIntelligenceDashboardRouteImport } from './routes/api/intelligence.dashboard'
import { Route as ApiIntelligenceQueryRouteImport } from './routes/api/intelligence.query'
import { Route as ApiIntelligenceSocialRouteImport } from './routes/api/intelligence.social'
import { Route as ApiCaseCaseIdBipRouteImport } from './routes/api/case.$caseId.bip'
import { Route as ApiCaseCaseIdCinRouteImport } from './routes/api/case.$caseId.cin'
import { Route as ApiCaseCaseIdSuggestionsRouteImport } from './routes/api/case.$caseId.suggestions'
import { Route as ApiCaseCaseIdSummaryRouteImport } from './routes/api/case.$caseId.summary'
import { Route as ApiCaseCaseIdTimelineRouteImport } from './routes/api/case.$caseId.timeline'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalystRoute = AnalystRouteImport.update({
  id: '/analyst',
  path: '/analyst',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigatorRoute = InvestigatorRouteImport.update({
  id: '/investigator',
  path: '/investigator',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicymakerRoute = PolicymakerRouteImport.update({
  id: '/policymaker',
  path: '/policymaker',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorRoute = SupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalystIndexRoute = AnalystIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnalystRoute,
} as any)
const AnalystCniRoute = AnalystCniRouteImport.update({
  id: '/cni',
  path: '/cni',
  getParentRoute: () => AnalystRoute,
} as any)
const AnalystPciRoute = AnalystPciRouteImport.update({
  id: '/pci',
  path: '/pci',
  getParentRoute: () => AnalystRoute,
} as any)
const AnalystReportsRoute = AnalystReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AnalystRoute,
} as any)
const AnalystSciRoute = AnalystSciRouteImport.update({
  id: '/sci',
  path: '/sci',
  getParentRoute: () => AnalystRoute,
} as any)
const ApiCasesRoute = ApiCasesRouteImport.update({
  id: '/api/cases',
  path: '/api/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeploymentRoute = ApiDeploymentRouteImport.update({
  id: '/api/deployment',
  path: '/api/deployment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNetworkRoute = ApiNetworkRouteImport.update({
  id: '/api/network',
  path: '/api/network',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersRoute = ApiOrdersRouteImport.update({
  id: '/api/orders',
  path: '/api/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPolicyImpactRoute = ApiPolicyImpactRouteImport.update({
  id: '/api/policy-impact',
  path: '/api/policy-impact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPolicySimulationRoute = ApiPolicySimulationRouteImport.update({
  id: '/api/policy-simulation',
  path: '/api/policy-simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPredictionsRoute = ApiPredictionsRouteImport.update({
  id: '/api/predictions',
  path: '/api/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportsRoute = ApiReportsRouteImport.update({
  id: '/api/reports',
  path: '/api/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResourcePlanningRoute = ApiResourcePlanningRouteImport.update({
  id: '/api/resource-planning',
  path: '/api/resource-planning',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiThreatsRoute = ApiThreatsRouteImport.update({
  id: '/api/threats',
  path: '/api/threats',
  getParentRoute: () => rootRouteImport,
} as any)
const InitializeRoleRoute = InitializeRoleRouteImport.update({
  id: '/initialize/$role',
  path: '/initialize/$role',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigatorIndexRoute = InvestigatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InvestigatorRoute,
} as any)
const InvestigatorBipRoute = InvestigatorBipRouteImport.update({
  id: '/bip',
  path: '/bip',
  getParentRoute: () => InvestigatorRoute,
} as any)
const InvestigatorCinRoute = InvestigatorCinRouteImport.update({
  id: '/cin',
  path: '/cin',
  getParentRoute: () => InvestigatorRoute,
} as any)
const InvestigatorHistoryRoute = InvestigatorHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => InvestigatorRoute,
} as any)
const PolicymakerIndexRoute = PolicymakerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PolicymakerRoute,
} as any)
const PolicymakerImpactRoute = PolicymakerImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => PolicymakerRoute,
} as any)
const PolicymakerReportsRoute = PolicymakerReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => PolicymakerRoute,
} as any)
const PolicymakerResourcesRoute = PolicymakerResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => PolicymakerRoute,
} as any)
const PolicymakerStrategyRoute = PolicymakerStrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => PolicymakerRoute,
} as any)
const SupervisorIndexRoute = SupervisorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SupervisorRoute,
} as any)
const SupervisorDeploymentRoute = SupervisorDeploymentRouteImport.update({
  id: '/deployment',
  path: '/deployment',
  getParentRoute: () => SupervisorRoute,
} as any)
const SupervisorOperationsRoute = SupervisorOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => SupervisorRoute,
} as any)
const SupervisorOrdersRoute = SupervisorOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => SupervisorRoute,
} as any)
const SupervisorThreatsRoute = SupervisorThreatsRouteImport.update({
  id: '/threats',
  path: '/threats',
  getParentRoute: () => SupervisorRoute,
} as any)
const WorkspaceRoleRoute = WorkspaceRoleRouteImport.update({
  id: '/workspace/$role',
  path: '/workspace/$role',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCaseCaseIdRoute = ApiCaseCaseIdRouteImport.update({
  id: '/api/case/$caseId',
  path: '/api/case/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDecisionScenarioRoute = ApiDecisionScenarioRouteImport.update({
  id: '/api/decision/scenario',
  path: '/api/decision/scenario',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDistrictOperationsRoute = ApiDistrictOperationsRouteImport.update({
  id: '/api/district/operations',
  path: '/api/district/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDistrictOverviewRoute = ApiDistrictOverviewRouteImport.update({
  id: '/api/district/overview',
  path: '/api/district/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGovernanceDashboardRoute = ApiGovernanceDashboardRouteImport.update({
  id: '/api/governance/dashboard',
  path: '/api/governance/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGovernanceQueryRoute = ApiGovernanceQueryRouteImport.update({
  id: '/api/governance/query',
  path: '/api/governance/query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGovernanceStrategyRoute = ApiGovernanceStrategyRouteImport.update({
  id: '/api/governance/strategy',
  path: '/api/governance/strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntelligenceDashboardRoute =
  ApiIntelligenceDashboardRouteImport.update({
    id: '/api/intelligence/dashboard',
    path: '/api/intelligence/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntelligenceQueryRoute = ApiIntelligenceQueryRouteImport.update({
  id: '/api/intelligence/query',
  path: '/api/intelligence/query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntelligenceSocialRoute = ApiIntelligenceSocialRouteImport.update({
  id: '/api/intelligence/social',
  path: '/api/intelligence/social',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCaseCaseIdBipRoute = ApiCaseCaseIdBipRouteImport.update({
  id: '/bip',
  path: '/bip',
  getParentRoute: () => ApiCaseCaseIdRoute,
} as any)
const ApiCaseCaseIdCinRoute = ApiCaseCaseIdCinRouteImport.update({
  id: '/cin',
  path: '/cin',
  getParentRoute: () => ApiCaseCaseIdRoute,
} as any)
const ApiCaseCaseIdSuggestionsRoute =
  ApiCaseCaseIdSuggestionsRouteImport.update({
    id: '/suggestions',
    path: '/suggestions',
    getParentRoute: () => ApiCaseCaseIdRoute,
  } as any)
const ApiCaseCaseIdSummaryRoute = ApiCaseCaseIdSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => ApiCaseCaseIdRoute,
} as any)
const ApiCaseCaseIdTimelineRoute = ApiCaseCaseIdTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => ApiCaseCaseIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyst': typeof AnalystRouteWithChildren
  '/architecture': typeof ArchitectureRoute
  '/auth': typeof AuthRoute
  '/console': typeof ConsoleRoute
  '/investigator': typeof InvestigatorRouteWithChildren
  '/policymaker': typeof PolicymakerRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/supervisor': typeof SupervisorRouteWithChildren
  '/analyst/cni': typeof AnalystCniRoute
  '/analyst/pci': typeof AnalystPciRoute
  '/analyst/reports': typeof AnalystReportsRoute
  '/analyst/sci': typeof AnalystSciRoute
  '/api/cases': typeof ApiCasesRoute
  '/api/chat': typeof ApiChatRoute
  '/api/deployment': typeof ApiDeploymentRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/network': typeof ApiNetworkRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/policy-impact': typeof ApiPolicyImpactRoute
  '/api/policy-simulation': typeof ApiPolicySimulationRoute
  '/api/predictions': typeof ApiPredictionsRoute
  '/api/reports': typeof ApiReportsRoute
  '/api/resource-planning': typeof ApiResourcePlanningRoute
  '/api/threats': typeof ApiThreatsRoute
  '/initialize/$role': typeof InitializeRoleRoute
  '/investigator/bip': typeof InvestigatorBipRoute
  '/investigator/cin': typeof InvestigatorCinRoute
  '/investigator/history': typeof InvestigatorHistoryRoute
  '/policymaker/impact': typeof PolicymakerImpactRoute
  '/policymaker/reports': typeof PolicymakerReportsRoute
  '/policymaker/resources': typeof PolicymakerResourcesRoute
  '/policymaker/strategy': typeof PolicymakerStrategyRoute
  '/supervisor/deployment': typeof SupervisorDeploymentRoute
  '/supervisor/operations': typeof SupervisorOperationsRoute
  '/supervisor/orders': typeof SupervisorOrdersRoute
  '/supervisor/threats': typeof SupervisorThreatsRoute
  '/workspace/$role': typeof WorkspaceRoleRoute
  '/analyst/': typeof AnalystIndexRoute
  '/investigator/': typeof InvestigatorIndexRoute
  '/policymaker/': typeof PolicymakerIndexRoute
  '/supervisor/': typeof SupervisorIndexRoute
  '/api/case/$caseId': typeof ApiCaseCaseIdRouteWithChildren
  '/api/decision/scenario': typeof ApiDecisionScenarioRoute
  '/api/district/operations': typeof ApiDistrictOperationsRoute
  '/api/district/overview': typeof ApiDistrictOverviewRoute
  '/api/governance/dashboard': typeof ApiGovernanceDashboardRoute
  '/api/governance/query': typeof ApiGovernanceQueryRoute
  '/api/governance/strategy': typeof ApiGovernanceStrategyRoute
  '/api/intelligence/dashboard': typeof ApiIntelligenceDashboardRoute
  '/api/intelligence/query': typeof ApiIntelligenceQueryRoute
  '/api/intelligence/social': typeof ApiIntelligenceSocialRoute
  '/api/case/$caseId/bip': typeof ApiCaseCaseIdBipRoute
  '/api/case/$caseId/cin': typeof ApiCaseCaseIdCinRoute
  '/api/case/$caseId/suggestions': typeof ApiCaseCaseIdSuggestionsRoute
  '/api/case/$caseId/summary': typeof ApiCaseCaseIdSummaryRoute
  '/api/case/$caseId/timeline': typeof ApiCaseCaseIdTimelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/auth': typeof AuthRoute
  '/console': typeof ConsoleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/analyst/cni': typeof AnalystCniRoute
  '/analyst/pci': typeof AnalystPciRoute
  '/analyst/reports': typeof AnalystReportsRoute
  '/analyst/sci': typeof AnalystSciRoute
  '/api/cases': typeof ApiCasesRoute
  '/api/chat': typeof ApiChatRoute
  '/api/deployment': typeof ApiDeploymentRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/network': typeof ApiNetworkRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/policy-impact': typeof ApiPolicyImpactRoute
  '/api/policy-simulation': typeof ApiPolicySimulationRoute
  '/api/predictions': typeof ApiPredictionsRoute
  '/api/reports': typeof ApiReportsRoute
  '/api/resource-planning': typeof ApiResourcePlanningRoute
  '/api/threats': typeof ApiThreatsRoute
  '/initialize/$role': typeof InitializeRoleRoute
  '/investigator/bip': typeof InvestigatorBipRoute
  '/investigator/cin': typeof InvestigatorCinRoute
  '/investigator/history': typeof InvestigatorHistoryRoute
  '/policymaker/impact': typeof PolicymakerImpactRoute
  '/policymaker/reports': typeof PolicymakerReportsRoute
  '/policymaker/resources': typeof PolicymakerResourcesRoute
  '/policymaker/strategy': typeof PolicymakerStrategyRoute
  '/supervisor/deployment': typeof SupervisorDeploymentRoute
  '/supervisor/operations': typeof SupervisorOperationsRoute
  '/supervisor/orders': typeof SupervisorOrdersRoute
  '/supervisor/threats': typeof SupervisorThreatsRoute
  '/workspace/$role': typeof WorkspaceRoleRoute
  '/analyst': typeof AnalystIndexRoute
  '/investigator': typeof InvestigatorIndexRoute
  '/policymaker': typeof PolicymakerIndexRoute
  '/supervisor': typeof SupervisorIndexRoute
  '/api/case/$caseId': typeof ApiCaseCaseIdRouteWithChildren
  '/api/decision/scenario': typeof ApiDecisionScenarioRoute
  '/api/district/operations': typeof ApiDistrictOperationsRoute
  '/api/district/overview': typeof ApiDistrictOverviewRoute
  '/api/governance/dashboard': typeof ApiGovernanceDashboardRoute
  '/api/governance/query': typeof ApiGovernanceQueryRoute
  '/api/governance/strategy': typeof ApiGovernanceStrategyRoute
  '/api/intelligence/dashboard': typeof ApiIntelligenceDashboardRoute
  '/api/intelligence/query': typeof ApiIntelligenceQueryRoute
  '/api/intelligence/social': typeof ApiIntelligenceSocialRoute
  '/api/case/$caseId/bip': typeof ApiCaseCaseIdBipRoute
  '/api/case/$caseId/cin': typeof ApiCaseCaseIdCinRoute
  '/api/case/$caseId/suggestions': typeof ApiCaseCaseIdSuggestionsRoute
  '/api/case/$caseId/summary': typeof ApiCaseCaseIdSummaryRoute
  '/api/case/$caseId/timeline': typeof ApiCaseCaseIdTimelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyst': typeof AnalystRouteWithChildren
  '/architecture': typeof ArchitectureRoute
  '/auth': typeof AuthRoute
  '/console': typeof ConsoleRoute
  '/investigator': typeof InvestigatorRouteWithChildren
  '/policymaker': typeof PolicymakerRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/supervisor': typeof SupervisorRouteWithChildren
  '/analyst/cni': typeof AnalystCniRoute
  '/analyst/pci': typeof AnalystPciRoute
  '/analyst/reports': typeof AnalystReportsRoute
  '/analyst/sci': typeof AnalystSciRoute
  '/api/cases': typeof ApiCasesRoute
  '/api/chat': typeof ApiChatRoute
  '/api/deployment': typeof ApiDeploymentRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/network': typeof ApiNetworkRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/policy-impact': typeof ApiPolicyImpactRoute
  '/api/policy-simulation': typeof ApiPolicySimulationRoute
  '/api/predictions': typeof ApiPredictionsRoute
  '/api/reports': typeof ApiReportsRoute
  '/api/resource-planning': typeof ApiResourcePlanningRoute
  '/api/threats': typeof ApiThreatsRoute
  '/initialize/$role': typeof InitializeRoleRoute
  '/investigator/bip': typeof InvestigatorBipRoute
  '/investigator/cin': typeof InvestigatorCinRoute
  '/investigator/history': typeof InvestigatorHistoryRoute
  '/policymaker/impact': typeof PolicymakerImpactRoute
  '/policymaker/reports': typeof PolicymakerReportsRoute
  '/policymaker/resources': typeof PolicymakerResourcesRoute
  '/policymaker/strategy': typeof PolicymakerStrategyRoute
  '/supervisor/deployment': typeof SupervisorDeploymentRoute
  '/supervisor/operations': typeof SupervisorOperationsRoute
  '/supervisor/orders': typeof SupervisorOrdersRoute
  '/supervisor/threats': typeof SupervisorThreatsRoute
  '/workspace/$role': typeof WorkspaceRoleRoute
  '/analyst/': typeof AnalystIndexRoute
  '/investigator/': typeof InvestigatorIndexRoute
  '/policymaker/': typeof PolicymakerIndexRoute
  '/supervisor/': typeof SupervisorIndexRoute
  '/api/case/$caseId': typeof ApiCaseCaseIdRouteWithChildren
  '/api/decision/scenario': typeof ApiDecisionScenarioRoute
  '/api/district/operations': typeof ApiDistrictOperationsRoute
  '/api/district/overview': typeof ApiDistrictOverviewRoute
  '/api/governance/dashboard': typeof ApiGovernanceDashboardRoute
  '/api/governance/query': typeof ApiGovernanceQueryRoute
  '/api/governance/strategy': typeof ApiGovernanceStrategyRoute
  '/api/intelligence/dashboard': typeof ApiIntelligenceDashboardRoute
  '/api/intelligence/query': typeof ApiIntelligenceQueryRoute
  '/api/intelligence/social': typeof ApiIntelligenceSocialRoute
  '/api/case/$caseId/bip': typeof ApiCaseCaseIdBipRoute
  '/api/case/$caseId/cin': typeof ApiCaseCaseIdCinRoute
  '/api/case/$caseId/suggestions': typeof ApiCaseCaseIdSuggestionsRoute
  '/api/case/$caseId/summary': typeof ApiCaseCaseIdSummaryRoute
  '/api/case/$caseId/timeline': typeof ApiCaseCaseIdTimelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyst'
    | '/architecture'
    | '/auth'
    | '/console'
    | '/investigator'
    | '/policymaker'
    | '/sitemap.xml'
    | '/supervisor'
    | '/analyst/cni'
    | '/analyst/pci'
    | '/analyst/reports'
    | '/analyst/sci'
    | '/api/cases'
    | '/api/chat'
    | '/api/deployment'
    | '/api/history'
    | '/api/network'
    | '/api/orders'
    | '/api/policy-impact'
    | '/api/policy-simulation'
    | '/api/predictions'
    | '/api/reports'
    | '/api/resource-planning'
    | '/api/threats'
    | '/initialize/$role'
    | '/investigator/bip'
    | '/investigator/cin'
    | '/investigator/history'
    | '/policymaker/impact'
    | '/policymaker/reports'
    | '/policymaker/resources'
    | '/policymaker/strategy'
    | '/supervisor/deployment'
    | '/supervisor/operations'
    | '/supervisor/orders'
    | '/supervisor/threats'
    | '/workspace/$role'
    | '/analyst/'
    | '/investigator/'
    | '/policymaker/'
    | '/supervisor/'
    | '/api/case/$caseId'
    | '/api/decision/scenario'
    | '/api/district/operations'
    | '/api/district/overview'
    | '/api/governance/dashboard'
    | '/api/governance/query'
    | '/api/governance/strategy'
    | '/api/intelligence/dashboard'
    | '/api/intelligence/query'
    | '/api/intelligence/social'
    | '/api/case/$caseId/bip'
    | '/api/case/$caseId/cin'
    | '/api/case/$caseId/suggestions'
    | '/api/case/$caseId/summary'
    | '/api/case/$caseId/timeline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/auth'
    | '/console'
    | '/sitemap.xml'
    | '/analyst/cni'
    | '/analyst/pci'
    | '/analyst/reports'
    | '/analyst/sci'
    | '/api/cases'
    | '/api/chat'
    | '/api/deployment'
    | '/api/history'
    | '/api/network'
    | '/api/orders'
    | '/api/policy-impact'
    | '/api/policy-simulation'
    | '/api/predictions'
    | '/api/reports'
    | '/api/resource-planning'
    | '/api/threats'
    | '/initialize/$role'
    | '/investigator/bip'
    | '/investigator/cin'
    | '/investigator/history'
    | '/policymaker/impact'
    | '/policymaker/reports'
    | '/policymaker/resources'
    | '/policymaker/strategy'
    | '/supervisor/deployment'
    | '/supervisor/operations'
    | '/supervisor/orders'
    | '/supervisor/threats'
    | '/workspace/$role'
    | '/analyst'
    | '/investigator'
    | '/policymaker'
    | '/supervisor'
    | '/api/case/$caseId'
    | '/api/decision/scenario'
    | '/api/district/operations'
    | '/api/district/overview'
    | '/api/governance/dashboard'
    | '/api/governance/query'
    | '/api/governance/strategy'
    | '/api/intelligence/dashboard'
    | '/api/intelligence/query'
    | '/api/intelligence/social'
    | '/api/case/$caseId/bip'
    | '/api/case/$caseId/cin'
    | '/api/case/$caseId/suggestions'
    | '/api/case/$caseId/summary'
    | '/api/case/$caseId/timeline'
  id:
    | '__root__'
    | '/'
    | '/analyst'
    | '/architecture'
    | '/auth'
    | '/console'
    | '/investigator'
    | '/policymaker'
    | '/sitemap.xml'
    | '/supervisor'
    | '/analyst/cni'
    | '/analyst/pci'
    | '/analyst/reports'
    | '/analyst/sci'
    | '/api/cases'
    | '/api/chat'
    | '/api/deployment'
    | '/api/history'
    | '/api/network'
    | '/api/orders'
    | '/api/policy-impact'
    | '/api/policy-simulation'
    | '/api/predictions'
    | '/api/reports'
    | '/api/resource-planning'
    | '/api/threats'
    | '/initialize/$role'
    | '/investigator/bip'
    | '/investigator/cin'
    | '/investigator/history'
    | '/policymaker/impact'
    | '/policymaker/reports'
    | '/policymaker/resources'
    | '/policymaker/strategy'
    | '/supervisor/deployment'
    | '/supervisor/operations'
    | '/supervisor/orders'
    | '/supervisor/threats'
    | '/workspace/$role'
    | '/analyst/'
    | '/investigator/'
    | '/policymaker/'
    | '/supervisor/'
    | '/api/case/$caseId'
    | '/api/decision/scenario'
    | '/api/district/operations'
    | '/api/district/overview'
    | '/api/governance/dashboard'
    | '/api/governance/query'
    | '/api/governance/strategy'
    | '/api/intelligence/dashboard'
    | '/api/intelligence/query'
    | '/api/intelligence/social'
    | '/api/case/$caseId/bip'
    | '/api/case/$caseId/cin'
    | '/api/case/$caseId/suggestions'
    | '/api/case/$caseId/summary'
    | '/api/case/$caseId/timeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalystRoute: typeof AnalystRouteWithChildren
  ArchitectureRoute: typeof ArchitectureRoute
  AuthRoute: typeof AuthRoute
  ConsoleRoute: typeof ConsoleRoute
  InvestigatorRoute: typeof InvestigatorRouteWithChildren
  PolicymakerRoute: typeof PolicymakerRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupervisorRoute: typeof SupervisorRouteWithChildren
  ApiCasesRoute: typeof ApiCasesRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiDeploymentRoute: typeof ApiDeploymentRoute
  ApiHistoryRoute: typeof ApiHistoryRoute
  ApiNetworkRoute: typeof ApiNetworkRoute
  ApiOrdersRoute: typeof ApiOrdersRoute
  ApiPolicyImpactRoute: typeof ApiPolicyImpactRoute
  ApiPolicySimulationRoute: typeof ApiPolicySimulationRoute
  ApiPredictionsRoute: typeof ApiPredictionsRoute
  ApiReportsRoute: typeof ApiReportsRoute
  ApiResourcePlanningRoute: typeof ApiResourcePlanningRoute
  ApiThreatsRoute: typeof ApiThreatsRoute
  InitializeRoleRoute: typeof InitializeRoleRoute
  WorkspaceRoleRoute: typeof WorkspaceRoleRoute
  ApiCaseCaseIdRoute: typeof ApiCaseCaseIdRouteWithChildren
  ApiDecisionScenarioRoute: typeof ApiDecisionScenarioRoute
  ApiDistrictOperationsRoute: typeof ApiDistrictOperationsRoute
  ApiDistrictOverviewRoute: typeof ApiDistrictOverviewRoute
  ApiGovernanceDashboardRoute: typeof ApiGovernanceDashboardRoute
  ApiGovernanceQueryRoute: typeof ApiGovernanceQueryRoute
  ApiGovernanceStrategyRoute: typeof ApiGovernanceStrategyRoute
  ApiIntelligenceDashboardRoute: typeof ApiIntelligenceDashboardRoute
  ApiIntelligenceQueryRoute: typeof ApiIntelligenceQueryRoute
  ApiIntelligenceSocialRoute: typeof ApiIntelligenceSocialRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyst': {
      id: '/analyst'
      path: '/analyst'
      fullPath: '/analyst'
      preLoaderRoute: typeof AnalystRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigator': {
      id: '/investigator'
      path: '/investigator'
      fullPath: '/investigator'
      preLoaderRoute: typeof InvestigatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policymaker': {
      id: '/policymaker'
      path: '/policymaker'
      fullPath: '/policymaker'
      preLoaderRoute: typeof PolicymakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor': {
      id: '/supervisor'
      path: '/supervisor'
      fullPath: '/supervisor'
      preLoaderRoute: typeof SupervisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyst/': {
      id: '/analyst/'
      path: '/'
      fullPath: '/analyst/'
      preLoaderRoute: typeof AnalystIndexRouteImport
      parentRoute: typeof AnalystRoute
    }
    '/analyst/cni': {
      id: '/analyst/cni'
      path: '/cni'
      fullPath: '/analyst/cni'
      preLoaderRoute: typeof AnalystCniRouteImport
      parentRoute: typeof AnalystRoute
    }
    '/analyst/pci': {
      id: '/analyst/pci'
      path: '/pci'
      fullPath: '/analyst/pci'
      preLoaderRoute: typeof AnalystPciRouteImport
      parentRoute: typeof AnalystRoute
    }
    '/analyst/reports': {
      id: '/analyst/reports'
      path: '/reports'
      fullPath: '/analyst/reports'
      preLoaderRoute: typeof AnalystReportsRouteImport
      parentRoute: typeof AnalystRoute
    }
    '/analyst/sci': {
      id: '/analyst/sci'
      path: '/sci'
      fullPath: '/analyst/sci'
      preLoaderRoute: typeof AnalystSciRouteImport
      parentRoute: typeof AnalystRoute
    }
    '/api/cases': {
      id: '/api/cases'
      path: '/api/cases'
      fullPath: '/api/cases'
      preLoaderRoute: typeof ApiCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/deployment': {
      id: '/api/deployment'
      path: '/api/deployment'
      fullPath: '/api/deployment'
      preLoaderRoute: typeof ApiDeploymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/network': {
      id: '/api/network'
      path: '/api/network'
      fullPath: '/api/network'
      preLoaderRoute: typeof ApiNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders': {
      id: '/api/orders'
      path: '/api/orders'
      fullPath: '/api/orders'
      preLoaderRoute: typeof ApiOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/policy-impact': {
      id: '/api/policy-impact'
      path: '/api/policy-impact'
      fullPath: '/api/policy-impact'
      preLoaderRoute: typeof ApiPolicyImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/policy-simulation': {
      id: '/api/policy-simulation'
      path: '/api/policy-simulation'
      fullPath: '/api/policy-simulation'
      preLoaderRoute: typeof ApiPolicySimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/predictions': {
      id: '/api/predictions'
      path: '/api/predictions'
      fullPath: '/api/predictions'
      preLoaderRoute: typeof ApiPredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports': {
      id: '/api/reports'
      path: '/api/reports'
      fullPath: '/api/reports'
      preLoaderRoute: typeof ApiReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resource-planning': {
      id: '/api/resource-planning'
      path: '/api/resource-planning'
      fullPath: '/api/resource-planning'
      preLoaderRoute: typeof ApiResourcePlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/threats': {
      id: '/api/threats'
      path: '/api/threats'
      fullPath: '/api/threats'
      preLoaderRoute: typeof ApiThreatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/initialize/$role': {
      id: '/initialize/$role'
      path: '/initialize/$role'
      fullPath: '/initialize/$role'
      preLoaderRoute: typeof InitializeRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigator/': {
      id: '/investigator/'
      path: '/'
      fullPath: '/investigator/'
      preLoaderRoute: typeof InvestigatorIndexRouteImport
      parentRoute: typeof InvestigatorRoute
    }
    '/investigator/bip': {
      id: '/investigator/bip'
      path: '/bip'
      fullPath: '/investigator/bip'
      preLoaderRoute: typeof InvestigatorBipRouteImport
      parentRoute: typeof InvestigatorRoute
    }
    '/investigator/cin': {
      id: '/investigator/cin'
      path: '/cin'
      fullPath: '/investigator/cin'
      preLoaderRoute: typeof InvestigatorCinRouteImport
      parentRoute: typeof InvestigatorRoute
    }
    '/investigator/history': {
      id: '/investigator/history'
      path: '/history'
      fullPath: '/investigator/history'
      preLoaderRoute: typeof InvestigatorHistoryRouteImport
      parentRoute: typeof InvestigatorRoute
    }
    '/policymaker/': {
      id: '/policymaker/'
      path: '/'
      fullPath: '/policymaker/'
      preLoaderRoute: typeof PolicymakerIndexRouteImport
      parentRoute: typeof PolicymakerRoute
    }
    '/policymaker/impact': {
      id: '/policymaker/impact'
      path: '/impact'
      fullPath: '/policymaker/impact'
      preLoaderRoute: typeof PolicymakerImpactRouteImport
      parentRoute: typeof PolicymakerRoute
    }
    '/policymaker/reports': {
      id: '/policymaker/reports'
      path: '/reports'
      fullPath: '/policymaker/reports'
      preLoaderRoute: typeof PolicymakerReportsRouteImport
      parentRoute: typeof PolicymakerRoute
    }
    '/policymaker/resources': {
      id: '/policymaker/resources'
      path: '/resources'
      fullPath: '/policymaker/resources'
      preLoaderRoute: typeof PolicymakerResourcesRouteImport
      parentRoute: typeof PolicymakerRoute
    }
    '/policymaker/strategy': {
      id: '/policymaker/strategy'
      path: '/strategy'
      fullPath: '/policymaker/strategy'
      preLoaderRoute: typeof PolicymakerStrategyRouteImport
      parentRoute: typeof PolicymakerRoute
    }
    '/supervisor/': {
      id: '/supervisor/'
      path: '/'
      fullPath: '/supervisor/'
      preLoaderRoute: typeof SupervisorIndexRouteImport
      parentRoute: typeof SupervisorRoute
    }
    '/supervisor/deployment': {
      id: '/supervisor/deployment'
      path: '/deployment'
      fullPath: '/supervisor/deployment'
      preLoaderRoute: typeof SupervisorDeploymentRouteImport
      parentRoute: typeof SupervisorRoute
    }
    '/supervisor/operations': {
      id: '/supervisor/operations'
      path: '/operations'
      fullPath: '/supervisor/operations'
      preLoaderRoute: typeof SupervisorOperationsRouteImport
      parentRoute: typeof SupervisorRoute
    }
    '/supervisor/orders': {
      id: '/supervisor/orders'
      path: '/orders'
      fullPath: '/supervisor/orders'
      preLoaderRoute: typeof SupervisorOrdersRouteImport
      parentRoute: typeof SupervisorRoute
    }
    '/supervisor/threats': {
      id: '/supervisor/threats'
      path: '/threats'
      fullPath: '/supervisor/threats'
      preLoaderRoute: typeof SupervisorThreatsRouteImport
      parentRoute: typeof SupervisorRoute
    }
    '/workspace/$role': {
      id: '/workspace/$role'
      path: '/workspace/$role'
      fullPath: '/workspace/$role'
      preLoaderRoute: typeof WorkspaceRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/case/$caseId': {
      id: '/api/case/$caseId'
      path: '/api/case/$caseId'
      fullPath: '/api/case/$caseId'
      preLoaderRoute: typeof ApiCaseCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/decision/scenario': {
      id: '/api/decision/scenario'
      path: '/api/decision/scenario'
      fullPath: '/api/decision/scenario'
      preLoaderRoute: typeof ApiDecisionScenarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/district/operations': {
      id: '/api/district/operations'
      path: '/api/district/operations'
      fullPath: '/api/district/operations'
      preLoaderRoute: typeof ApiDistrictOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/district/overview': {
      id: '/api/district/overview'
      path: '/api/district/overview'
      fullPath: '/api/district/overview'
      preLoaderRoute: typeof ApiDistrictOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/governance/dashboard': {
      id: '/api/governance/dashboard'
      path: '/api/governance/dashboard'
      fullPath: '/api/governance/dashboard'
      preLoaderRoute: typeof ApiGovernanceDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/governance/query': {
      id: '/api/governance/query'
      path: '/api/governance/query'
      fullPath: '/api/governance/query'
      preLoaderRoute: typeof ApiGovernanceQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/governance/strategy': {
      id: '/api/governance/strategy'
      path: '/api/governance/strategy'
      fullPath: '/api/governance/strategy'
      preLoaderRoute: typeof ApiGovernanceStrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/intelligence/dashboard': {
      id: '/api/intelligence/dashboard'
      path: '/api/intelligence/dashboard'
      fullPath: '/api/intelligence/dashboard'
      preLoaderRoute: typeof ApiIntelligenceDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/intelligence/query': {
      id: '/api/intelligence/query'
      path: '/api/intelligence/query'
      fullPath: '/api/intelligence/query'
      preLoaderRoute: typeof ApiIntelligenceQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/intelligence/social': {
      id: '/api/intelligence/social'
      path: '/api/intelligence/social'
      fullPath: '/api/intelligence/social'
      preLoaderRoute: typeof ApiIntelligenceSocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/case/$caseId/bip': {
      id: '/api/case/$caseId/bip'
      path: '/bip'
      fullPath: '/api/case/$caseId/bip'
      preLoaderRoute: typeof ApiCaseCaseIdBipRouteImport
      parentRoute: typeof ApiCaseCaseIdRoute
    }
    '/api/case/$caseId/cin': {
      id: '/api/case/$caseId/cin'
      path: '/cin'
      fullPath: '/api/case/$caseId/cin'
      preLoaderRoute: typeof ApiCaseCaseIdCinRouteImport
      parentRoute: typeof ApiCaseCaseIdRoute
    }
    '/api/case/$caseId/suggestions': {
      id: '/api/case/$caseId/suggestions'
      path: '/suggestions'
      fullPath: '/api/case/$caseId/suggestions'
      preLoaderRoute: typeof ApiCaseCaseIdSuggestionsRouteImport
      parentRoute: typeof ApiCaseCaseIdRoute
    }
    '/api/case/$caseId/summary': {
      id: '/api/case/$caseId/summary'
      path: '/summary'
      fullPath: '/api/case/$caseId/summary'
      preLoaderRoute: typeof ApiCaseCaseIdSummaryRouteImport
      parentRoute: typeof ApiCaseCaseIdRoute
    }
    '/api/case/$caseId/timeline': {
      id: '/api/case/$caseId/timeline'
      path: '/timeline'
      fullPath: '/api/case/$caseId/timeline'
      preLoaderRoute: typeof ApiCaseCaseIdTimelineRouteImport
      parentRoute: typeof ApiCaseCaseIdRoute
    }
  }
}

interface AnalystRouteChildren {
  AnalystCniRoute: typeof AnalystCniRoute
  AnalystPciRoute: typeof AnalystPciRoute
  AnalystReportsRoute: typeof AnalystReportsRoute
  AnalystSciRoute: typeof AnalystSciRoute
  AnalystIndexRoute: typeof AnalystIndexRoute
}

const AnalystRouteChildren: AnalystRouteChildren = {
  AnalystCniRoute: AnalystCniRoute,
  AnalystPciRoute: AnalystPciRoute,
  AnalystReportsRoute: AnalystReportsRoute,
  AnalystSciRoute: AnalystSciRoute,
  AnalystIndexRoute: AnalystIndexRoute,
}

const AnalystRouteWithChildren =
  AnalystRoute._addFileChildren(AnalystRouteChildren)

interface InvestigatorRouteChildren {
  InvestigatorBipRoute: typeof InvestigatorBipRoute
  InvestigatorCinRoute: typeof InvestigatorCinRoute
  InvestigatorHistoryRoute: typeof InvestigatorHistoryRoute
  InvestigatorIndexRoute: typeof InvestigatorIndexRoute
}

const InvestigatorRouteChildren: InvestigatorRouteChildren = {
  InvestigatorBipRoute: InvestigatorBipRoute,
  InvestigatorCinRoute: InvestigatorCinRoute,
  InvestigatorHistoryRoute: InvestigatorHistoryRoute,
  InvestigatorIndexRoute: InvestigatorIndexRoute,
}

const InvestigatorRouteWithChildren = InvestigatorRoute._addFileChildren(
  InvestigatorRouteChildren,
)

interface PolicymakerRouteChildren {
  PolicymakerImpactRoute: typeof PolicymakerImpactRoute
  PolicymakerReportsRoute: typeof PolicymakerReportsRoute
  PolicymakerResourcesRoute: typeof PolicymakerResourcesRoute
  PolicymakerStrategyRoute: typeof PolicymakerStrategyRoute
  PolicymakerIndexRoute: typeof PolicymakerIndexRoute
}

const PolicymakerRouteChildren: PolicymakerRouteChildren = {
  PolicymakerImpactRoute: PolicymakerImpactRoute,
  PolicymakerReportsRoute: PolicymakerReportsRoute,
  PolicymakerResourcesRoute: PolicymakerResourcesRoute,
  PolicymakerStrategyRoute: PolicymakerStrategyRoute,
  PolicymakerIndexRoute: PolicymakerIndexRoute,
}

const PolicymakerRouteWithChildren = PolicymakerRoute._addFileChildren(
  PolicymakerRouteChildren,
)

interface SupervisorRouteChildren {
  SupervisorDeploymentRoute: typeof SupervisorDeploymentRoute
  SupervisorOperationsRoute: typeof SupervisorOperationsRoute
  SupervisorOrdersRoute: typeof SupervisorOrdersRoute
  SupervisorThreatsRoute: typeof SupervisorThreatsRoute
  SupervisorIndexRoute: typeof SupervisorIndexRoute
}

const SupervisorRouteChildren: SupervisorRouteChildren = {
  SupervisorDeploymentRoute: SupervisorDeploymentRoute,
  SupervisorOperationsRoute: SupervisorOperationsRoute,
  SupervisorOrdersRoute: SupervisorOrdersRoute,
  SupervisorThreatsRoute: SupervisorThreatsRoute,
  SupervisorIndexRoute: SupervisorIndexRoute,
}

const SupervisorRouteWithChildren = SupervisorRoute._addFileChildren(
  SupervisorRouteChildren,
)

interface ApiCaseCaseIdRouteChildren {
  ApiCaseCaseIdBipRoute: typeof ApiCaseCaseIdBipRoute
  ApiCaseCaseIdCinRoute: typeof ApiCaseCaseIdCinRoute
  ApiCaseCaseIdSuggestionsRoute: typeof ApiCaseCaseIdSuggestionsRoute
  ApiCaseCaseIdSummaryRoute: typeof ApiCaseCaseIdSummaryRoute
  ApiCaseCaseIdTimelineRoute: typeof ApiCaseCaseIdTimelineRoute
}

const ApiCaseCaseIdRouteChildren: ApiCaseCaseIdRouteChildren = {
  ApiCaseCaseIdBipRoute: ApiCaseCaseIdBipRoute,
  ApiCaseCaseIdCinRoute: ApiCaseCaseIdCinRoute,
  ApiCaseCaseIdSuggestionsRoute: ApiCaseCaseIdSuggestionsRoute,
  ApiCaseCaseIdSummaryRoute: ApiCaseCaseIdSummaryRoute,
  ApiCaseCaseIdTimelineRoute: ApiCaseCaseIdTimelineRoute,
}

const ApiCaseCaseIdRouteWithChildren = ApiCaseCaseIdRoute._addFileChildren(
  ApiCaseCaseIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalystRoute: AnalystRouteWithChildren,
  ArchitectureRoute: ArchitectureRoute,
  AuthRoute: AuthRoute,
  ConsoleRoute: ConsoleRoute,
  InvestigatorRoute: InvestigatorRouteWithChildren,
  PolicymakerRoute: PolicymakerRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupervisorRoute: SupervisorRouteWithChildren,
  ApiCasesRoute: ApiCasesRoute,
  ApiChatRoute: ApiChatRoute,
  ApiDeploymentRoute: ApiDeploymentRoute,
  ApiHistoryRoute: ApiHistoryRoute,
  ApiNetworkRoute: ApiNetworkRoute,
  ApiOrdersRoute: ApiOrdersRoute,
  ApiPolicyImpactRoute: ApiPolicyImpactRoute,
  ApiPolicySimulationRoute: ApiPolicySimulationRoute,
  ApiPredictionsRoute: ApiPredictionsRoute,
  ApiReportsRoute: ApiReportsRoute,
  ApiResourcePlanningRoute: ApiResourcePlanningRoute,
  ApiThreatsRoute: ApiThreatsRoute,
  InitializeRoleRoute: InitializeRoleRoute,
  WorkspaceRoleRoute: WorkspaceRoleRoute,
  ApiCaseCaseIdRoute: ApiCaseCaseIdRouteWithChildren,
  ApiDecisionScenarioRoute: ApiDecisionScenarioRoute,
  ApiDistrictOperationsRoute: ApiDistrictOperationsRoute,
  ApiDistrictOverviewRoute: ApiDistrictOverviewRoute,
  ApiGovernanceDashboardRoute: ApiGovernanceDashboardRoute,
  ApiGovernanceQueryRoute: ApiGovernanceQueryRoute,
  ApiGovernanceStrategyRoute: ApiGovernanceStrategyRoute,
  ApiIntelligenceDashboardRoute: ApiIntelligenceDashboardRoute,
  ApiIntelligenceQueryRoute: ApiIntelligenceQueryRoute,
  ApiIntelligenceSocialRoute: ApiIntelligenceSocialRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
